-- SQL Schema for Supabase

-- 1. Create Items Table
CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    image TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Orders Table
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    items JSONB NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Seed Default Items
INSERT INTO items (name, price, image) VALUES
('Matcha Meadow', 40.00, 'https://images.unsplash.com/photo-1627847483517-5a5744c4ec3c?q=80&w=400'),
('Taro Cloud', 40.00, 'https://images.unsplash.com/photo-1619158403521-ed9795026d47?q=80&w=400'),
('Green Zenith', 40.00, 'https://images.unsplash.com/photo-1515442261904-6c3e7c30a781?q=80&w=400'),
('The Classic Tee', 40.00, 'https://images.unsplash.com/photo-1558857563-b371f30ca6a5?q=80&w=400');
