-- SQL Schema for Supabase

-- 1. Create Items Table
CREATE TABLE if not exists items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    image TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Orders Table
create table if not exists orders (
  id bigint generated by default as identity primary key,
  items jsonb not null,
  total int not null,
  created_at timestamptz default now()
);

-- 3. Enable RLS and add Policy for Public Inserts
alter table orders enable row level security;

create policy "Allow public insert orders"
on orders
for insert
with check (true);

-- 4. Seed Default Items (Optional if already seeded)
INSERT INTO items (name, price, image)
SELECT 'Matcha Meadow', 40.00, 'https://images.unsplash.com/photo-1627847483517-5a5744c4ec3c?q=80&w=400'
WHERE NOT EXISTS (SELECT 1 FROM items WHERE name = 'Matcha Meadow');

INSERT INTO items (name, price, image)
SELECT 'Taro Cloud', 40.00, 'https://images.unsplash.com/photo-1619158403521-ed9795026d47?q=80&w=400'
WHERE NOT EXISTS (SELECT 1 FROM items WHERE name = 'Taro Cloud');

INSERT INTO items (name, price, image)
SELECT 'Green Zenith', 40.00, 'https://images.unsplash.com/photo-1515442261904-6c3e7c30a781?q=80&w=400'
WHERE NOT EXISTS (SELECT 1 FROM items WHERE name = 'Green Zenith');

INSERT INTO items (name, price, image)
SELECT 'The Classic Tee', 40.00, 'https://images.unsplash.com/photo-1558857563-b371f30ca6a5?q=80&w=400'
WHERE NOT EXISTS (SELECT 1 FROM items WHERE name = 'The Classic Tee');
